import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>mi primera chamba </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          <p className='cool-font'>holaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</p> 
          <br></br>
          <p className='yei'>Yeeeiii, al fin no me tira error :) </p>
        </div>
        
        <div>
          <p className='feita'>aaa, estoy bien feita          </p>
        </div>
        <div>
          <p className='ahora'>y ahora?</p> <br></br>
          <p className='ahora'>mañana <p className='seguir'>sigo </p>jugando</p>
          <p className='ahora'>no me deja poner una imagen :(</p>
        </div>
        
      </main>
    </>
  )
}
// no me deja poner este codigo <image src='public\jesus-bailando.gif' alt="jesus bailando"></image>
 //import Image from 'next/image';

//const MiComponente = () => {
//  return (
//    <div>
//      <h1>Mi Componente con Imagen</h1>
//      <Image src='/jesus-bailando.gif' alt='jesus bailando' width={400} height={300} />
//    </div>
//  );
//};
//
//export default MiComponente;


//
//
//
//
//
//